### ISSUE TITLE
Prototype warming up sandbox cache

### ISSUE THREAD

**Issue by ManasJayanth** [esy/pesy#100]
Pesy sets up the CI for the user's project and the CI is setup such that we create zip of all dependencies so that PRs can re-use previous build artifacts for faster runs.

With a few tweaks, pesy can also implement a feature to pull the zip file and warm up local cache right after we clone the project.

What do we need?
1. Use `esy export-dependencies` on the CI and zip it
2. Fetch the zip and run `esy import-dependencies`

Tentatively, this could be implemented as `pesy warmup` sub command to the npm-cli.

Feedback and querries are very welcome.

**Comment by sibis** [comment]
@prometheansacrifice correct me if my understanding is correct here,
we need a `pesy warmup` command support, which internally runs `esy export-dependencies` and `esy import-dependencies`. Also, can you throw some lights on the part which are the files to be part of zip and you have mentioned in the first line that the current implementation creates the zip of all the dependencies, I don't find it anywhere.

**Comment by prometheansacrifice** [comment]
Indeed, it's not obvious where exactly the zip file is being created.

This is what I had in mind

https://github.com/esy/pesy/blob/5562d9387ba62704f6505c505c906b82f5d73a51/.ci/utils/publish-build-cache.yml#L8

It compresses the dependencies cache into a tar ball. (The format tar.gz or zip doesn't matter very much. We are free to choose which ever we like). However, the cached tarball in not in the best form to be downloaded. Reason: https://github.com/esy-ocaml/hello-reason/pull/53#discussion_r355165182 When the compressed form is created from `export-dependencies`, they can be easily relocated from one system to another - in this case from CI to our local machine. This is the primary intention behind #1 `Use esy export-dependencies on the CI and zip it`

**Comment by prometheansacrifice** [comment]
You could look for inspiration in this file (from hell-reason) here: https://github.com/esy-ocaml/hello-reason/blob/master/.ci/utils/publish-build-cache.yml

**Comment by prometheansacrifice** [comment]
@sibis I have taken care of subtask no. 1 You just need to look at no. 2

**Comment by prometheansacrifice** [comment]
Here is an implementation of subtask 2 written in bash, for reference

https://gist.github.com/prometheansacrifice/a6c5406d7315d081583854469247526f

**Comment by sibis** [comment]
@prometheansacrifice Here is the implementation to fetch and extract written in JS, https://github.com/sibis/pesy/blob/restore-build-cache/.ci/utils/fetch-and-import.js

**Comment by ManasJayanth** [comment]
Fixed by #127
