### ISSUE TITLE
Modes support:

### ISSUE THREAD

**Issue by jordwalke** [esy/pesy#138]
I'm not sure if this is a new form for dune, but now the modes must/may be defined as described in the Dune manual

> For instance the following modes fields are all equivalent:
> (modes (exe object shared_object))
> (modes ((best exe)
> (best object)
> (best shared_object)))
> And finally, you can use the special mode byte_complete for building a bytecode executable as a > native selfcontained executable.

So apparently modes may be:
```
(modes (M k1 k2 ..kn) (N j1 j2 ...jn))
```

And `k` may now be `js`, which pesy doesn't seem to support.

When I try to do this in pesy:
```
      "modes": [
        ["byte", "exe"],
        ["byte", "js"]
      ]
```

I get the error: 
```
pesy: internal error, uncaught exception:
      Lib__FieldTypes.ConversionException("Expected string. Actual list")
```
And when I just specify the JS one: `"modes": ["byte", "js"]` I get this error:

```
pesy: internal error, uncaught exception:
      Lib__Executable.Mode.InvalidBinaryKind(0)
```

Maybe we could clean up some of the errors too, but would be nice to support the more recent form of modes. 

What about this approach to many of the fields: Instead of requiring a list in one place, or a list of lists in another - we accept any form, and merely warn when the form was not what is expected, but print the most reasonable interpretation (list of lists becomes `( ( ) () )` etc.
That way if the dune spec changes at least it can still generate valid dune even if it doesn't match our expectations.

**Comment by melwyn95** [comment]
As per the [Linking modes section of the Dune docs](https://dune.readthedocs.io/en/stable/dune-files.html#linking-modes) 
we need to support `modes` as
```
modes: [ <binary-kind>                          ]
modes: [ <binary-kind>, +                       ]
modes: [ <compilation-mode>, <binary-kind>      ]
modes: [ [ <compilation-mode>, <binary-kind> ]+ ]

// we could aslo support this
modes: "<binary-kind>"
modes: "(<binary-kind><white-space>+)+"
```
where `+` means repeated 1 or more times

Please correct me If I missed anything. 
Also there is mention of `byte_complete` in docs, 
I didn't fully understand what needs to done in case of `byte_complete` as it is not classified as  `<compilation-mode>`

**Comment by ManasJayanth** [comment]
@melwyn95 Yes, my understanding is the same. I propose fixing the `modes` schema to be a array of entries, where each entry can be either a string or a 2-tuple array.

```re
type entry = String(v) | Array(v);
type modes = array(entry)
```

The tuple structure is as per the grammar you posted.

**Comment by melwyn95** [comment]
@ManasJayanth once we add support for multiple modes, in order to make it useful we'll need to provide support for multiple executables, we can take that up as a separate issue.

**Comment by ManasJayanth** [comment]
@melwyn95 Sure!
