### ISSUE TITLE
c_names vs. foreign stubs.

### ISSUE THREAD

**Issue by jordwalke** [esy/pesy#142]
I used the `cNames` field in pesy, which creates the `c_names` field in dune, but it looks like Dune deprecated that field, and says to use `foreign_stubs`.

> `Error: 'c_names' was deleted in version 2.0 of the dune language. Use the
> (foreign_stubs ...) field instead.`

How should we deal with this? Can we detect which version of Dune is being used?

**Comment by ulrikstrid** [comment]
We could look at the dune-project to see lang-version
