### ISSUE TITLE
Skip aliasing if imported name is same as exported

### ISSUE THREAD

**Issue by ManasJayanth** [esy/pesy#171]
The new npm style require syntax works by emiting modules that alias the namespace like this

```
(rule
    (with-stdout-to FooCliPesyModules.re
        (run echo  "module AliasedDep = DepNamespace;\
                  \nmodule AliasedDep2 = Dep2Namespace;")))
```

If users, especially experienced ones, know the namespace of the library beforehand and the use same,

```json
"imports": [
  "Re = require('@opam/re')",
  "Pastel = require('@reason-native/pastel/lib')"
]
```

...creates...

```
(rule
    (with-stdout-to WebsiteDbCliPesyModules.re
        (run echo  "module Re = Re;\
                  \nmodule Pastel = Pastel;")))
```

This causes unnecessary indirection, noticed especially when merlin/ocamllsp shows long aliased names in the editor autocomplete.

By skipping (therefore linking such libraries directly), we could get cleaner editor completions.

**Comment by ulrikstrid** [comment]
😍

**Comment by tatchi** [comment]
@ManasJayanth I think this one can be closed now :)

**Comment by ManasJayanth** [comment]
Thanks @tatchi That was a great PR!
