### ISSUE TITLE
Misleading error message: foo.library not found

### ISSUE THREAD

**Issue by ManasJayanth** [esy/pesy#194]
```json
        "Library = require('foo/library')"
```

When the `library` folder was renamed to `src/lib`, Dune threw "`foo.library` not found.

This can be confusing. `pesy` should have pointed to the `require()` statement and pointed out the incorrect (because outdated) library path.

**Comment by melwyn95** [comment]
should we add validation while reading the paths in require? (check if the path exists)

**Comment by ManasJayanth** [comment]
Yes, via findlib.

**Comment by ManasJayanth** [comment]
Related TODO - https://github.com/esy/pesy/issues/49
