### ISSUE TITLE
Pesy (native) alpha question.

### ISSUE THREAD

**Issue by jordwalke** [esy/pesy#20]
From Discord:
> One thing that came up is that it's not clear how to use the bin field. Can you specify multiple binaries per directory? The syntax appears to allow that. If so, how do you specify which "requires" accompany each binary in that directory?
> Or is the convention that each directory can have one binary, but all of the binaries in a directory must have the same set of requires?

I believe Dune only really allows one executable per directory (unless you do a bunch of complex stuff). Please feel free to close this with a simple answer.

**Comment by prometheansacrifice** [comment]
The idea is that just like dune, some day, we support multiple executables. But at the moment we support only one executable. I'll keep this issue open until some docs are added (which are long overdue)
