### ISSUE TITLE
(Azure Pipelines, pesy@next) error: unable to resolve command: pesy-configure

### ISSUE THREAD

**Issue by Schniz** [esy/pesy#24]
Seems like the `esy-build-steps.yml` file has a typo that cause the following error on Azure Pipelines:

```
error: unable to resolve command: pesy-configure
```

https://github.com/esy/pesy/blob/fba113444137392aa288e1484a4408dde6726478/assets/azure-pipeline-templates/pesy-esy-build-steps.template.yml#L11-L12

I believe it should be just `esy pesy`, or am I missing something?

**Comment by prometheansacrifice** [comment]
@Schniz You are right. It should be `esy pesy`

A few esy versions back we some issue with installing assets inside the sandbox because of which we had to create a separate binary called `pesy-configure`.

**Comment by prometheansacrifice** [comment]
Closed by #25
