### ISSUE TITLE
Pesy must advise on an OCaml compiler version

### ISSUE THREAD

**Issue by prometheansacrifice** [esy/pesy#30]
If someone updates their pesy (local), it's possible that it depends on a different compiler version. This might lead to conflicts.

Why not set it as '*'? In the past, this has cause minor issues like when ocaml 4.8.0 was made available it cause the wrong version/outdated version of deps which were incorrectly packaged. to be pulled. Advising a compiler version (or a resolutions field) to the user would be nice way to handle this.

**Comment by ulrikstrid** [comment]
Wouldn't setting `"ocaml": "<4.9.0" be enough?

**Comment by prometheansacrifice** [comment]
Indeed, we can close this with PR using the `<=` operator

**Comment by prometheansacrifice** [comment]
Closing this for now
