### ISSUE TITLE
Create a new repo with pesy is failing at the moment

### ISSUE THREAD

**Issue by sync** [esy/pesy#35]
https://gist.github.com/sync/27740d5f52983b979883ba961f24be77

`_/i/ocaml-4.7.1004-e5a2754f/lib/ocaml/topfind: Operation not permitted`

if you change your package to this it works (downgrading ocamlfind to pre 1.8.0):

```
 "dependencies": {
    "@opam/dune": "*",
    "@esy-ocaml/reason": "*",
    "refmterr": "*",
    "ocaml": "<4.7.0",
    "pesy": "*",
    "@reason-native/rely": "*",
    "@opam/ocamlfind": "1.7.3"
  },
```

So it seems to be related to latest ocamlfind

I am using `pesy@0.5.0-alpha.4` and what i did was:

```
mkdir monorepo
cd monorepo
pesy
```

**Comment by andreypopp** [comment]
Please try again (make sure you removed esy.lock) — should work now.

**Comment by sync** [comment]
just tested on osx it's working now :-)
