### ISSUE TITLE
Investigate the use of Pastel for Bucklescript portion of the codebase

### ISSUE THREAD

**Issue by ManasJayanth** [esy/pesy#41]
Currently, we are using ANSI escape sequences. It would be ideal to something more readable like [Pastel](https://reason-native.com/docs/pastel/).

**Comment by ulrikstrid** [comment]
I think Pastel is only for native right now? I think we can use [chalk](https://www.npmjs.com/package/chalk) to get the same functionality but without the JSX API.

Or we can create bindings for it that can be compiled from JSX?

**Comment by prometheansacrifice** [comment]
Indeed, it is native only right now. But, under the hood, [it uses ANSI sequences too](https://github.com/facebookexperimental/reason-native/blob/master/src/pastel/Ansi.re), so strictly speaking this issue isn't related to pesy itself.

That being said, if logs get too messy we could writing bindings for Chalk
