### ISSUE TITLE
Check if directory is empty before initializing project

### ISSUE THREAD

**Issue by ulrikstrid** [esy/pesy#57]

**Comment by tatchi** [comment]
Hi,

I would be happy to try helping with this one :)

**Comment by ulrikstrid** [comment]
Hello @tatchi, thank you!

I think you basically have to add a check somewhere here: https://github.com/esy/pesy/blob/master/npm-cli/src/Pesy.re#L54
Let me know if you need any further assistance.

**Comment by tatchi** [comment]
Thanks for your help, it helps me a lot!

What should be the behaviour if we detect that the directory is not empty? What I can propose:

- Stoping and printing a message to inform the user that the directory should be empty.
- Inform the user that the directory is not empty and ask him if he still wants to continue [y/n]

What do you think?

**Comment by ulrikstrid** [comment]
We have thoughts about having versioned templates and maybe even a way to migrate to later versions. This is not something you have to think of here, but if you want to make something robust you could implement the [y/n] solution as we can then extend that to check if you're in a pesy project and see you if there are new versions ontop.

But the minimum useful thing is just stopping and printing a message.
