### ISSUE TITLE
refmterr should be devDependency.

### ISSUE THREAD

**Issue by jordwalke** [esy/pesy#72]
When I make a new pesy project, I usually place a couple of changes:

```
    "build": "dune build -p #{self.name}",
    "buildDev": "refmterr dune build -p #{self.name}",
```
Then I move `refmterr` to a devDependency. That's so that this avoids putting additional dependencies that are only needed for development time.

**Comment by prometheansacrifice** [comment]
Addressed by https://github.com/esy/pesy-reason-template/pull/5
